// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // Build output and generated native projects. `ios/` and `android/` are
    // regenerated by `expo prebuild`, so linting them reports on code we do
    // not own and cannot meaningfully fix.
    ignores: ["dist/*", "ios/*", "android/*", ".expo/*", "modules/*/android/build/*"],
  }
]);
